version: '3'
services:
  app:
    image: frontend:1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  
  tests:
    image: frontend:1
    volumes:
      - .:/app
    command: ["npm", "run", "test"]